services:
  web:
    build: .
    container_name: my-django
    ports:
      - "8888:8888"
    command: python manage.py runserver 0.0.0.0:8888
    volumes:
      - ./library:/usr/app/library/
    depends_on:
      - db
  db:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/usr/app/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    container_name: my-postgresql
volumes:
  postgres_data: null
